AnimalAdoptionWebSite/Controllers/KindController.cs
using AnimalAdoptionWebSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnimalAdoptionWebSite.Controllers
{
    public class KindController : Controller
    {
        private readonly Context context;

        public KindController(Context context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var listOfKind = context.Kinds.ToList();
            return View(listOfKind);
        }

        //Yeni tür eklemek için action
        [HttpGet]
        public IActionResult AddKind()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddKind(Kind kind)
        {
            context.Kinds.Add(kind);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        //Türü silmek için action
        public IActionResult DeleteKind(int id)
        {
            var fetchKind = context.Kinds.Where(x => x.KIND_ID == id).FirstOrDefault();
            context.Kinds.Remove(fetchKind);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        //id sini verdiğimizde, kind bulması için gereken action
        public IActionResult GetKind(int id)
        {
            var fetchKind = context.Kinds.Where(x => x.KIND_ID == id).FirstOrDefault();
            return View("UpdateKind", fetchKind);
        }

        //tür adını güncellemek için action
        public IActionResult UpdateKind(Kind kind)
        {
            var fetchKind = context.Kinds.Where(x => x.KIND_ID == kind.KIND_ID).FirstOrDefault();
            fetchKind.TYPE_NAME = kind.TYPE_NAME;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

AnimalAdoptionWebSite/Controllers/LoginController.cs
using AnimalAdoptionWebSite.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AnimalAdoptionWebSite.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        private readonly Context context;
        public LoginController(Context context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Admin admin = null, Member member = null)
        {
            var fetchAdmin = context.Admins.FirstOrDefault(x => x.MAIL == admin.MAIL && x.PASSWORD == admin.PASSWORD);
            var fetchMember = context.Members.FirstOrDefault(x => x.MAIL == member.MAIL && x.PASSWORD == member.PASSWORD);
            if (fetchAdmin != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name,admin.MAIL)
                };
                var adminIdentity = new ClaimsIdentity(claims, "a");
                ClaimsPrincipal principal = new ClaimsPrincipal(adminIdentity);
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index", "Animal");
            }
            else if (fetchMember != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name,member.MAIL)
                };
                var memberIdentity = new ClaimsIdentity(claims, "a");
                ClaimsPrincipal principal = new ClaimsPrincipal(memberIdentity);
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index", "MemberPage");
            }
            else
            {
                //TempData["error"] = "Bilgileriniz eksik veya hatali. Lutfen kontrol edin!";
                return View();
            }
        }

        //Oturum kapatma işlemi
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

    }
}

AnimalAdoptionWebSite/Controllers/MemberController.cs
using AnimalAdoptionWebSite.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnimalAdoptionWebSite.Controllers
{
    public class MemberController : Controller
    {
        private readonly Context context;
        public MemberController(Context context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var listOfMember = context.Members.ToList();
            return View(listOfMember);
        }

        //id sine göre üye bulma işlemi için action
        public IActionResult GetMember(int id)
        {
            var fetchMember = context.Members.Where(x => x.MEMBER_ID == id).FirstOrDefault();
            return View("UpdateMember", fetchMember);
        }

        //üye bilgilerini güncelleme işlemi için action
        public IActionResult UpdateMember(Member member)
        {
            var fetchMember = context.Members.Where(x => x.MEMBER_ID == member.MEMBER_ID).FirstOrDefault();
            fetchMember.NAMESURNAME = member.NAMESURNAME;
            fetchMember.MAIL = member.MAIL;
            //fetchMember.PASSWORD = member.PASSWORD;
            fetchMember.AGE = member.AGE;
            fetchMember.PHONENUMBER = member.PHONENUMBER;
            fetchMember.ADDRESS = member.ADDRESS;
            fetchMember.ABOUT = member.ABOUT;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        //member silme actionı
        public IActionResult DeleteMember(int id)
        {
            var fetchMember = context.Members.Where(x => x.MEMBER_ID == id).FirstOrDefault();
            context.Members.Remove(fetchMember);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

AnimalAdoptionWebSite/Controllers/RegisterController.cs
using AnimalAdoptionWebSite.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnimalAdoptionWebSite.Controllers
{
    [AllowAnonymous]
    public class RegisterController : Controller
    {
        private readonly Context context;
        public RegisterController(Context context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Member member)
        {
            context.Members.Add(member);
            context.SaveChanges();
            return RedirectToAction("Index","Home");
        }
    }
}

AnimalAdoptionWebSite/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/css/admin_layout.css" rel="stylesheet" />
</head>
<body>

    <div class="header">
        <a href="" class="logo btn">Hayvan Sahiplendirme</a>
        <div class="header-right">
            <a asp-controller="Animal" asp-action="Index" class="btn"><i>&nbsp;Hayvanlar</i></a>
            <a asp-controller="Member" asp-action="Index" class="btn"><i>&nbsp;Üyeler</i></a>
            <a asp-controller="Kind" asp-action="Index" class="btn"><i>&nbsp;Türler</i></a>
            <a asp-controller="AdoptionList" asp-action="Index" class="btn"><i>&nbsp;Sahiplenme kayıtları</i></a>
            <a asp-controller="Login" asp-action="Logout" class="btn btn-danger"><i>&nbsp;Çıkış</i></a>
        </div>
    </div>

    <div style="padding-left:20px">
        @RenderBody()
    </div>

</body>
</html>

AnimalAdoptionWebSite/Views/Shared/_Culture.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@inject Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> locOptions

@{
    var culture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    var cultureList = locOptions.Value.SupportedUICultures.Select(x => new SelectListItem { Value = x.Name, Text = localizer.GetString(x.Name) }).ToList();
    var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : $"~{ Context.Request.Path.Value}{Context.Request.QueryString }";
}

<div>
    <form asp-action="CultureManagement" asp-controller="MemberPage" method="post"
          asp-route-returnUrl="@returnUrl">
        <select name="culture" asp-for="@culture.RequestCulture.UICulture.Name" asp-items="cultureList"
                onchange="this.form.submit();"></select>
    </form>
</div>

AnimalAdoptionWebSite/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/css/home_layout.css" rel="stylesheet" />
</head>
<body>

    <div class="header">
        <a asp-controller="Home" asp-action="Index" class="logo btn">@localizer["Hayvan Sahiplendirme"]</a>
        <div class="header-right">
            <a href="#"><partial name="_Culture" /></a>
            <a asp-controller="Register" asp-action="Index" class="btn btn-outline-info"><i>&nbsp;@localizer["Üye Ol"]</i></a>
            <a asp-controller="Login" asp-action="Index" class="loginAdmin btn btn-info"><i>&nbsp;@localizer["Giriş Yap"]</i></a>
        </div>
    </div>

    <div style="padding-left:20px">
        @RenderBody()
    </div>

</body>
</html>

AnimalAdoptionWebSite/Views/Shared/_MemberLayout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/home_layout.css" rel="stylesheet" />
</head>
<body>

    <div class="header">
        <a asp-controller="MemberPage" asp-action="Index" class="logo btn">@localizer["Hayvan Sahiplendirme"]</a>
        <div class="header-right">
            <a href="#"><partial name="_Culture" /></a>
            <a asp-controller="MemberPage" asp-action="Profile" class="btn"><i class="glyphicon glyphicon-home">&nbsp;@localizer["Profil"]</i></a>
            <a asp-controller="MemberPage" asp-action="Index" class="btn"><i class="glyphicon glyphicon-home">&nbsp;@localizer["Hayvanlar"]</i></a>
            <a asp-controller="MemberPage" asp-action="ListOfAdoption" class="btn"><i class="glyphicon glyphicon-home">&nbsp;@localizer["Sahiplenme Geçmişi"]</i></a>
            <a asp-controller="Login" asp-action="Logout" class="btn btn-danger"><i>&nbsp;@localizer["Çıkış"]</i></a>
        </div>
    </div>

    <div style="padding-left:20px">
        @RenderBody()
    </div>

</body>
</html>