AnimalAdoptionWebSite/Controllers/CallApiController.cs
using AnimalAdoptionWebSite.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace AnimalAdoptionWebSite.Controllers
{
    public class CallApiController : Controller
    {
        private static readonly HttpClient httpClient = new HttpClient();

        public async Task<IActionResult> Index(int id)
        {
            List<Animal> fetchAnimal = new List<Animal>();
            var httpClient = new HttpClient();

            var response = await httpClient.GetAsync("https://localhost:44312/api/AnimalDetailsApi");
            string apiResponse = await response.Content.ReadAsStringAsync();
            fetchAnimal = JsonConvert.DeserializeObject<List<Animal>>(apiResponse);
            Animal str = fetchAnimal.Where(x => x.ANIMAL_ID == id).FirstOrDefault();
            return View(str);
        }
    }
}

AnimalAdoptionWebSite/Controllers/MemberPageController.cs
using AnimalAdoptionWebSite.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnimalAdoptionWebSite.Controllers
{
    public class MemberPageController : Controller
    {
        private readonly IHtmlLocalizer<MemberPageController> _localizer;
        private readonly Context context;

        public MemberPageController(Context context, IHtmlLocalizer<MemberPageController> localizer)
        {
            this.context = context;
            _localizer = localizer;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var ListOfAnimal = context.Animals.Where(x => x.STATUS == true).ToList();
            return View(ListOfAnimal);
        }

        [HttpPost, AllowAnonymous]
        public IActionResult CultureManagement(string culture, string returnUrl)
        {
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.Now.AddDays(30) });

            return LocalRedirect(returnUrl);
        }

        [HttpGet]
        public IActionResult Profile()
        {
            var fetchMemberMail = User.Identity.Name; //önce giriş yapanın mailini aldım
            //giriş yapanın mailinden ID sine ulaştım 
            var fetchMemberID = context.Members.Where(x => x.MAIL == fetchMemberMail).Select(y => y.MEMBER_ID).FirstOrDefault();
            //Id sini bildiğim üye nesnesini aldım
            var fetchMember = context.Members.Where(x => x.MEMBER_ID == fetchMemberID).FirstOrDefault();
            ViewBag.NameSurname = fetchMember.NAMESURNAME; //giriş yapanın isim soyismini viewbage aldım
            return View(fetchMember);
        }
        [HttpPost]
        public IActionResult Profile(Member member)
        {
            var fetchMember = context.Members.Where(x => x.MEMBER_ID == member.MEMBER_ID).FirstOrDefault();
            fetchMember.MAIL = member.MAIL;
            fetchMember.PASSWORD = member.PASSWORD;
            fetchMember.PHONENUMBER = member.PHONENUMBER;
            fetchMember.ADDRESS = member.ADDRESS;
            fetchMember.ABOUT = member.ABOUT;
            context.SaveChanges();
            return RedirectToAction("Index", "MemberPage");
        }

        //üyenin sahiplenme işlemi için oluşturduğum action
        public IActionResult CreateAdoption(int id)
        {
            var fetchMemberMail = User.Identity.Name; //önce giriş yapanın mailini aldım
            //giriş yapanın mailinden ID sine ulaştım 
            var fetchMemberID = context.Members.Where(x => x.MAIL == fetchMemberMail).Select(y => y.MEMBER_ID).FirstOrDefault();

            //sahiplenlen hayvanın durumunu false yapabilmek için gelen id ile animal nesnesini aldım
            var fetchAnimal = context.Animals.Where(x => x.ANIMAL_ID == id).FirstOrDefault();

            Adoption adoption = new Adoption();
            adoption.ANIMAL_ID = id;
            adoption.MEMBER_ID = fetchMemberID;
            adoption.DATE = DateTime.Now;
            fetchAnimal.STATUS = false; //hayvanın durumunu false yaptım
            context.Adoptions.Add(adoption);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        //kullanıcının sahiplenmelerine bakmasını sağlayan action
        public IActionResult ListOfAdoption()
        {
            var fetchMemberMail = User.Identity.Name; //önce giriş yapanın mailini aldım
            //giriş yapanın mailinden ID sine ulaştım 
            var fetchMemberID = context.Members.Where(x => x.MAIL == fetchMemberMail).Select(y => y.MEMBER_ID).FirstOrDefault();

            var listOfAdoption = context.Adoptions
                .Include(y => y.Member)
                .Include(z => z.Animal)
                .Where(x => x.MEMBER_ID == fetchMemberID)
                .ToList();
            return View(listOfAdoption);
        }

        public IActionResult DetailsOfAnimal(int id)
        {
            var fetchAnimalName = context.Animals.Where(x => x.ANIMAL_ID == id).Select(y => y.NAME).FirstOrDefault();
            ViewBag.animalName = fetchAnimalName;
            var fetchAnimal = context.Animals.Include(y=>y.Kind).Where(x => x.ANIMAL_ID == id).FirstOrDefault();
            return View(fetchAnimal);
        }
    }
}

AnimalAdoptionWebSite/Views/MemberPage/DetailsOfAnimal.cshtml
@model AnimalAdoptionWebSite.Models.Animal
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@{
    ViewData["Title"] = "DetailsOfAnimal";
    Layout = "~/Views/Shared/_MemberLayout.cshtml";
}
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

<h3 style="margin-top:30px;">@ViewBag.animalName @localizer["Bilgileri"]</h3>

<table class="table table-hover">
    <thead>
        <tr class="text-center">
            <th>
                @localizer["Tür Adı"]
            </th>
            <th>
                @localizer["İsim"]
            </th>
            <th>
                @localizer["Cins"]
            </th>
            <th>
                @localizer["Yaş"]
            </th>
            <th>
                @localizer["Şehir"]
            </th>
            <th>
                @localizer["Fotoğraf"]
            </th>
            <th>
                @localizer["Mevcut Durumu"]
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        <tr class="text-center">
            <td>
                @Html.DisplayFor(modelItem => modelItem.Kind.TYPE_NAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.NAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.GENUS)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.AGE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.CITY)
            </td>
            <td>
                <img src="@Model.PHOTO" alt="Alternate Text" style="width:80px;height:40px;"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.STATUS)
            </td>
            <td>
            </td>
        </tr>

    </tbody>
</table>

AnimalAdoptionWebSite/Views/MemberPage/Index.cshtml
@model IEnumerable<AnimalAdoptionWebSite.Models.Animal>
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MemberLayout.cshtml";
}

<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.js"></script>

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-3 m-3">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" style="width:auto; height:200px;" src="@item.PHOTO" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">
                            @localizer["İsmi"] : @Html.DisplayFor(modelItem => item.NAME) <br />
                            @localizer["Cinsi"] : @Html.DisplayFor(modelItem => item.GENUS) <br />
                            @localizer["Yaşı"] : @Html.DisplayFor(modelItem => item.AGE) <br />
                            @localizer["Şehir"] : @Html.DisplayFor(modelItem => item.CITY)
                        </p>
                        <a asp-action="CreateAdoption" asp-route-id="@item.ANIMAL_ID" onclick="myFunction()" class="btn btn-info">@localizer["Sahiplen"]</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@*metod şeklinde script yazıp alert çıkardım*@
<script>
    function myFunction() {
        alert("Sahiplenme işlemi başarıyla gerçekleşti.");
    }
</script>

AnimalAdoptionWebSite/Views/MemberPage/ListOfAdoption.cshtml
@model IEnumerable<AnimalAdoptionWebSite.Models.Adoption>
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@{
    ViewData["Title"] = "ListOfAdoption";
    Layout = "~/Views/Shared/_MemberLayout.cshtml";
}
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

<h3 style="margin-top:30px;">@localizer["Sahiplenme Geçmişiniz"] </h3>

<table class="table table-striped">
    <thead>
        <tr class="text-center">
            <th>
                @localizer["Üye"]
            </th>
            <th>
                @localizer["Hayvanın İsmi"]
            </th>
            <th>
                @localizer["Tarih"]
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="text-center">
                <td>
                    @Html.DisplayFor(modelItem => item.Member.NAMESURNAME)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Animal.NAME)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DATE)
                </td>
                <td>
                    @*<a asp-controller="CallApi" asp-action="Index" asp-route-id="@item.Animal.ANIMAL_ID" class="btn btn-success">@localizer["Detaylar"]</a>*@
                    <a asp-action="DetailsOfAnimal" asp-route-id="@item.Animal.ANIMAL_ID" class="btn btn-success">@localizer["Detaylar"]</a>
                </td>
            </tr>
        }
    </tbody>
</table>

AnimalAdoptionWebSite/Views/MemberPage/Profile.cshtml
@model AnimalAdoptionWebSite.Models.Member
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@{
    ViewData["Title"] = "Profile";
    Layout = "~/Views/Shared/_MemberLayout.cshtml";
}
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.js"></script>

<h3 style="margin-top:30px;">@localizer["Profilinize Hoşgeldiniz"] @ViewBag.NameSurname</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Profile">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MEMBER_ID" />
            <div class="form-group">
                <label class="control-label">@localizer["Mail"]</label>
                <input asp-for="MAIL" class="form-control" />
                <span asp-validation-for="MAIL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@localizer["Şifre"]</label>
                <input asp-for="PASSWORD" class="form-control" />
                <span asp-validation-for="PASSWORD" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@localizer["Telefon No"]</label>
                <input asp-for="PHONENUMBER" class="form-control" />
                <span asp-validation-for="PHONENUMBER" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@localizer["Adres"]</label>
                <input asp-for="ADDRESS" class="form-control" />
                <span asp-validation-for="ADDRESS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@localizer["Hakkında"]</label>
                <input asp-for="ABOUT" class="form-control" />
                <span asp-validation-for="ABOUT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" id="update" value=@localizer["Kaydet"] class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>

@*güncelleme işlemi gerçeleşirse mesaj çıkacak*@
<script>
    $('#update').click(function () {
        alert("Profilinizi güncelleme işlemi başarıyla tamamlandı.");
    });
</script>